      DOUBLE PRECISION FUNCTION GG2AAA (COS,L1234)
      IMPLICIT NONE
      DOUBLE PRECISION COS
      INTEGER L1234(4)
      DOUBLE PRECISION ONE,TWO,FOUR,HALF,PI
      PARAMETER ( ONE = 1D0, TWO = 2D0, FOUR = 4D0, HALF = 0.5D0 )
      PARAMETER ( PI = 3.141592654D0 )
      DOUBLE PRECISION S0,T0,A1,A2,A3,BS,BT
      DOUBLE PRECISION BSFN,BTFN,TSFN,TTFN,FRFN,IRS,IRT,IST
      DOUBLE COMPLEX   FFN
      DOUBLE PRECISION DDILOG
      S0 = -(ONE-COS)*HALF
      T0 = -(ONE+COS)*HALF
      A1 = DSQRT(ONE/(-S0))
      A2 = DSQRT(ONE/(-T0))
      A3 = DSQRT((5D0-COS**2)/(ONE-COS**2))
      BS = DSQRT((3D0-COS)/(ONE-COS))
      BT = DSQRT((3D0+COS)/(ONE+COS))
      BSFN = - ONE + HALF*BS*DLOG((BS+ONE)/(BS-ONE))
      BTFN = - ONE + HALF*BT*DLOG((BT+ONE)/(BT-ONE))
      TSFN = DLOG((BS+ONE)/(BS-ONE))**2/FOUR
      TTFN = DLOG((BT+ONE)/(BT-ONE))**2/FOUR
      IRS = FRFN(A1) + DREAL(FFN(S0,BS,A1))
      IRT = FRFN(A2) + DREAL(FFN(T0,BT,A2))
      IST = DREAL(FFN(S0,BS,A3) + FFN(T0,BT,A3))
      IF     ( ABS(L1234(1)+L1234(2)+L1234(3)+L1234(4)).EQ.4 ) THEN
         GG2AAA = ONE - HALF/S0 * IRS - HALF/T0 * IRT
     -        - HALF/(S0*T0) * IST
      ELSEIF ( ABS(L1234(1)+L1234(2)+L1234(3)+L1234(4)).EQ.2 ) THEN
         GG2AAA = ONE + (ONE+ONE/S0+ONE/T0) * (-PI**2/FOUR + TSFN + TTFN)
     -        - (ONE/T0+HALF/S0)*IRS - (ONE/S0+HALF/T0)*IRT
     -        - (ONE+HALF/(S0*T0))*IST
      ELSEIF ( ABS(L1234(1)+L1234(2)-L1234(3)-L1234(4)).EQ.4 ) THEN
         GG2AAA = - ONE - TWO*(ONE+TWO*S0)*BSFN - TWO*(ONE+TWO*T0)*BTFN
     -        + FOUR*S0*T0*(TSFN+TTFN) + HALF/S0*IRS + HALF/T0*IRT
     -        + (HALF/(S0*T0)-TWO-FOUR*S0*T0)*IST
      ELSEIF ( ABS(L1234(1)-L1234(2)-L1234(3)+L1234(4)).EQ.4 ) THEN
         GG2AAA = - ONE + TWO*(ONE-S0)/T0*(ONE+BSFN)
     -        - TWO*((ONE+S0**2)/T0**2-ONE/T0)*(-PI**2/FOUR+TSFN)
     -        + (ONE-HALF/T0)*(IRT+IST/S0)
      ELSEIF ( ABS(L1234(1)-L1234(2)+L1234(3)-L1234(4)).EQ.4 ) THEN
         GG2AAA = - ONE + TWO*(ONE-T0)/S0*(ONE+BTFN)
     -        - TWO*((ONE+T0**2)/S0**2-ONE/S0)*(-PI**2/FOUR+TTFN)
     -        + (ONE-HALF/S0)*(IRS+IST/T0)
      ELSE
         STOP
      ENDIF
      RETURN
      END

      DOUBLE PRECISION FUNCTION FRFN (A)
      IMPLICIT NONE
      DOUBLE PRECISION A
      DOUBLE PRECISION ONE,TWO,PI
      PARAMETER ( ONE = 1D0, TWO = 2D0 )
      PARAMETER ( PI = 3.141592654D0 )
      DOUBLE COMPLEX DL1,DL2
      INCLUDE 'CHAPLIN.INC'
      Z   = DCMPLX(A/(A+ONE),0D0)
      DL1 = HPL2(0,1,Z)
      Z   = DCMPLX((A-ONE)/A,0D0)
      DL2 = HPL2(0,1,Z)
      FRFN = ( DLOG(A)**2 + DLOG(ONE+A)**2 - TWO*DLOG(A)*DLOG(A-ONE)
     -     - TWO*PI**2/3D0 + TWO*DREAL(DL1) + TWO*DREAL(DL2) ) / (TWO*A)
      RETURN
      END
      
      DOUBLE COMPLEX FUNCTION FFN (S,B,A)
      IMPLICIT NONE
      DOUBLE PRECISION S,A,B
      DOUBLE PRECISION ONE,TWO,EPS
      PARAMETER ( ONE = 1D0, TWO = 2D0, EPS = 1D-10 )
      DOUBLE COMPLEX DL1,DL2,DL3,DL4
      INCLUDE 'CHAPLIN.INC'
      Z = DCMPLX((A+ONE)/(A+B),0D0)
      DL1 = HPL2(0,1,Z)
      Z = DCMPLX((A-ONE)/(A+B),0D0)
      DL2 = HPL2(0,1,Z)
      Z = DCMPLX((A+ONE)/(A-B),0D0)
      DL3 = HPL2(0,1,Z)
      Z = DCMPLX((A-ONE)/(A-B),0D0)
      DL4 = HPL2(0,1,Z)
      FFN = ( LOG((S-DCMPLX(0D0,EPS))*(A**2-B**2)) * DLOG((A+ONE)/(A-ONE))
     -     - DL1 + DL2 - DL3 + DL4 ) / (TWO*A)
      RETURN
      END
