      PROGRAM MAIN
      IMPLICIT NONE
      DOUBLE PRECISION RS, COS, MUR
      DOUBLE PRECISION S, T, U
      INTEGER L1234(4)
      DOUBLE COMPLEX GG2AABFD1, GG2AABFD2
      EXTERNAL GG2AABFD1, GG2AABFD2
      DOUBLE COMPLEX BFDFL, BFDFSL
      EXTERNAL BFDFL, BFDFSL
      DOUBLE COMPLEX AMP1,FL, FSL, AMP2
      DATA L1234/-1,1,1,1/
      RS = 300D0
      COS = 0D0
      MUR = 100D0
      AMP1 = GG2AABFD1(RS,COS,L1234)
      S = RS**2
      T = -S/2D0*(1D0+COS)
      U = -S/2D0*(1D0-COS)
      FL = BFDFL(S,T,U,L1234)
      FSL = BFDFSL(S,T,U,L1234)
      AMP2 = GG2AABFD2(RS,COS,MUR,L1234)
      PRINT *, AMP1
      PRINT *, FL
      PRINT *, FSL
      PRINT *, AMP2
      STOP
      END
